language: node_js
node_js:
  - 12.4.0
# commands to install dependencies
install:
  - npm install --save qunit
  - npm install --save esm
  - npm install --save eslint
  - npm install --save eslint-plugin-jsdoc
# commands to run tests
script:
  - node --require esm $(which qunit)
  - eslint --global resources --global input *.js
  - "eslint --global QUnit --global resources --rule 'max-len: 0' --rule 'max-lines-per-function: 0' test/*.js"
