language: node_js
node_js:
  - 12.4.0
# command to install dependencies
install:
  - npm install --save qunit
  - npm install --save esm
  - npm install --save eslint
  - npm install --save eslint-plugin-jsdoc
# command to run tests
script:
  - node --require esm $(which qunit)
  - eslint --global resources *.js
